<template>
  <div>
    <v-row>
      <v-img
        :src="require('../assets/AniMapLogo2.png')"
        class="ma-5"
        contain
        height="200"
      ></v-img>
        <br>
    </v-row>
  </div>
</template>
